# Generated by Django 5.1.6 on 2025-03-28 16:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.BinaryField(
                blank=True, null=True, validators=[home.models.validate_image_size]
            ),
        ),
    ]
