# Generated by Django 5.1.6 on 2025-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default_post.jpg", upload_to="post/"),
        ),
    ]
